% Code for a 1D tensegrity structure
% Inputs: initial positions and forces
% Outputs: final positions
% Version 0.1 by Caleb Swain on 2023/11/13 

close all
clear

% create a while loop
% Find the rigidity matrix
% Calculate tau = J^T*F
% use tau to get x_dot
% x_i+1 = x_i + dt*x_dot
% end while loop

% create a vector of positions
x1 = 0; % x position of node 1
x2 = 1; % x position of node 2
x = [x1; x2]; % vector of x positions
y = [0; 0]; % vector of y positions for 1D
plot(x, y, ".-b") % plots our structure
pause(10)

L = 1; % length of rod 1

x1_dot = 0; % linear velocity of node 1 in x direction
x2_dot = 1; % linear velocity of node 2 in x direction
x_dot = [x1_dot; x2_dot]; % vector of linear velocities in x direction

% L_dot = (x1 - x2)/L*x1_dot + (x2 - x1)/L*x2_dot
% L_dot = [(x1-x2)/L, (x2-x1)/L]*[x1_dot; x2_dot]
R = [(x1-x2)/L; (x2-x1)/L]; % rigidity matrix in 1D

% fix nodes by removing their rows
R(1,:) = [];
x(1,:) = [];

F = [-1]; % vector of forces applied to the structure
tau = R.'\-F; % calculates the internal forces
% tau(1) is the reaction force at node 1
% tau(2) is the force generated by rod 1

k = [1000]; % vector of stiffnesses of the rods
% F = -k*delta_x or tau = -k*delta_x
% delta_x = -k\tau
delta_x = -k\tau;
x = x + delta_x;

x = [x1, x];
plot(x, y, ".-r")