import numpy as np

doublePendulumConfig: dict = dict({'axisLength': 2,
                                   'barConnectivityMatrix': np.array([[1, 2], [2, 3]]),
                                   'coordinateNodeArray': np.array([[0, 0, 0], [np.sqrt(2) / 2, -np.sqrt(2) / 2, 0], [np.sqrt(2), -np.sqrt(2), 0]]),
                                   'createVideo': True,
                                   'damping': .001,
                                   'dt': .001,
                                   'filename': 'doublePendulumTest',
                                   'forcesOnNodesArray': np.array([[0, 0, 0], [-0.5 * 9.8, -9.8, -0.5 * 9.8], [0, 0, 0]]),
                                   'initialRotation': 0,
                                   'nonConstantForces': False,
                                   'numOfBars': 2,
                                   'numOfNode': 3,
                                   'numOfPinned': 1,
                                   'numOfStrings': 2,
                                   'initialVelocities': np.zeros([3, 3]),
                                   'pinnedNodes': list([1]),
                                   'prestress': 1,
                                   'saveHistory': False,
                                   'showPlot': False,
                                   'stringConnectivityMatrix': np.array([[1, 2], [2, 3]]),
                                   'tf': 5,
                                   'useController': False,
                                   'useGround': False
                                   })

icosahedronConfig: dict = dict({'axisLength': 5,
                                'barConnectivityMatrix': np.array([[1, 2], [3, 4], [5, 7], [6, 8], [9, 10], [11, 12]]),
                                'coordinateNodeArray': np.array([[1, 1.618 + 1.618, 0], [1, -1.618 + 1.618, 0], [-1, 1.618 + 1.618, 0],
                                                                 [-1, -1.618 + 1.618, 0], [1.618, 0 + 1.618, 1], [1.618, 0 + 1.618, -1],
                                                                 [-1.618, 0 + 1.618, 1], [-1.618, 0 + 1.618, -1], [0, 1 + 1.618, 1.618],
                                                                 [0, 1 + 1.618, -1.618], [0, -1 + 1.618, 1.618], [0, -1 + 1.618, -1.61]]),
                                'createVideo': True,
                                'damping': 2,
                                'dt': .001,
                                'filename': 'IcosahedronTest',
                                'forcesOnNodesArray': np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                                                                [-10., -10., -10., -10., -10., -10., -10., -10., -10., -10., -10., -10.],
                                                                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]),

                                'initialRotation': -41.80901 / 2,
                                'nonConstantForces': True,
                                'numOfBars': 6,
                                'numOfNode': 12,
                                'numOfPinned': 0,
                                'numOfStrings': 30,
                                'initialVelocities': np.zeros([3, 12]),
                                'prestress': .7,
                                'pinnedNodes': list([]),
                                'saveHistory': False,
                                'showPlot': False,
                                'stringConnectivityMatrix': np.array([[1, 3], [1, 5], [1, 6], [1, 9], [1, 10], [2, 4], [2, 5], [2, 6], [2, 11], [2, 12],
                                                                      [3, 7], [3, 8], [3, 9], [3, 10], [4, 7], [4, 8], [4, 11], [4, 12], [5, 6], [5, 9],
                                                                      [5, 11], [6, 10], [6, 12], [7, 8], [7, 9], [7, 11], [8, 10], [8, 12], [9, 11],
                                                                      [10, 12]]),
                                'tf': 10,
                                'useController': True,
                                'useGround': True
                                })

tensegrityJointConfig: dict = dict({'axisLength': 3,
                                    'barConnectivityMatrix': np.array([[9, 3], [9, 4], [9, 5], [10, 6], [10, 7], [10, 8], [1, 9], [2, 10]]),
                                    'coordinateNodeArray': np.array([[0, 0, np.sqrt(3) / 6], [0, -5, np.sqrt(3) / 6], [0, -3.5, np.sqrt(3) / 2],
                                                                     [1 / 2, -3.5, 0], [-1 / 2, -3.5, 0], [1 / 2, -2.5, np.sqrt(3) / 3],
                                                                     [0, -2.5, -np.sqrt(3) / 6], [-1 / 2, -2.5, np.sqrt(3) / 3], [0, -2.5, np.sqrt(3) / 6],
                                                                     [0, -3.5, np.sqrt(3) / 6]]),
                                    'createVideo': False,
                                    'damping': .001,
                                    'dt': .001,
                                    'filename': 'tensegrityJointTest',
                                    'forcesOnNodesArray': np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                                                                    [0, -10, 0, 0, 0, 0, 0, 0, 0, 0],
                                                                    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]),
                                    'initialRotation': 0,
                                    'nonConstantForces': False,
                                    'numOfBars': 8,
                                    'numOfNode': 10,
                                    'numOfPinned': 1,
                                    'numOfStrings': 24,
                                    'initialVelocities': np.zeros([3, 10]),
                                    'pinnedNodes': list([1]),
                                    'prestress': .7,
                                    'saveHistory': False,
                                    'showPlot': True,
                                    'stringConnectivityMatrix': np.array([[1, 3], [1, 4], [1, 5], [3, 4], [3, 5], [4, 5], [3, 6], [3, 8], [4, 7], [4, 6],
                                                                          [5, 8], [5, 7], [6, 7], [6, 8], [7, 8], [6, 2], [7, 2], [8, 2], [3, 10], [4, 10],
                                                                          [5, 10], [6, 9], [7, 9], [8, 9]]),
                                    'tf': .05,
                                    'useController': False,
                                    'useGround': False
                                    })
